# Generated by Django 6.1 on 2026-08-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet_classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planetclass',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='planetclass',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='planetclass',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='planetclass',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
