# Generated by Django 6.1 on 2026-08-15 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('planetclass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetDiscovery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('planet_name', models.CharField(max_length=100)),
                ('galaxy', models.CharField(max_length=100)),
                ('star_system', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('discovery_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('planetdiscovery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planetclass.planetclass')),
            ],
        ),
    ]
