# Generated by Django 6.1 on 2026-08-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Planets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planet", models.CharField(max_length=200)),
                ("galaxy", models.CharField(max_length=200)),
                ("star_system", models.CharField(max_length=200)),
                ("discovery_date", models.DateField()),
                ("owner", models.CharField(max_length=200)),
                ("planet_class", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
